# Basic Google Cloud Info
project_id: "<PROJECT_ID>"
dataset_id: "<DATASET_ID>"
location: "us"
connection_id: "cloud_ai_resources"

# Input Data Locations
patient_data_gcs_path: "gs://<PROJECT_ID>-patient-profiles/*.txt"
clinical_reports_gcs_path: "gs://<PROJECT_ID>-clinical-trials-docs/*.pdf"

# Advanced (Optional)
model_name: "cssr_reports_model"
