# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import sys

from google.api_core.client_info import ClientInfo
from google.cloud import bigquery


def run_ingestion(
    project_id: str,
    dataset_id: str,
    connection_id: str,
    patient_gcs_uri: str,
    trials_gcs_uri: str,
    model_name: str,
):
    """
    Triggers the BigQuery Stored Procedures to ingest unstructured clinical
    data from GCS. This script simulates a task orchestrator (like Apache
    Airflow or Cloud Run) invoking the procedures that were generated by
    the parameterize.py engine.
    """
    client_info = ClientInfo(user_agent="cloud-solutions/data-to-ai-nb-v2")
    client = bigquery.Client(project=project_id, client_info=client_info)

    print(
        f"Starting ingestion process for project: {project_id}, "
        f"dataset: {dataset_id}..."
    )

    # 1. Trigger Patient Profile Ingestion Procedure
    print(f"\n--- Ingesting Patient Profiles from {patient_gcs_uri} ---")
    patient_query = f"""
        CALL `{project_id}.{dataset_id}.IngestPatientProfiles`();
    """
    try:
        query_job = client.query(patient_query)
        query_job.result()  # Waits for the job to complete
        print("✅ Patient Profile ingestion completed successfully.")
    except Exception as e:
        print(f"❌ Error during Patient Profile ingestion: {e}")
        sys.exit(1)

    # 2. Trigger Clinical Trial Reports Ingestion Procedure
    print(f"\n--- Ingesting Clinical Trial Reports from {trials_gcs_uri} ---")
    trial_query = f"""
        CALL `{project_id}.{dataset_id}.IngestClinicalTrials`();
    """
    try:
        query_job = client.query(trial_query)
        query_job.result()  # Waits for the job to complete
        print("✅ Clinical Trial Report ingestion completed successfully.")
    except Exception as e:
        print(f"❌ Error during Clinical Trial Report ingestion: {e}")
        sys.exit(1)

    print("\n🎉 All ingestion pipelines executed successfully!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Orchestrate unstructured data ingestion into BigQuery."
    )

    # Defaulting to the known dev project settings, but allowing overrides
    # for testing purposes.
    parser.add_argument(
        "--project_id", type=str, default="<PROJECT_ID>", help="GCP Project ID"
    )
    parser.add_argument(
        "--dataset_id",
        type=str,
        default="<DATASET_ID>",
        help="Target BigQuery Dataset",
    )
    parser.add_argument(
        "--connection_id",
        type=str,
        default="<PROJECT_ID>.us.cloud_ai_resources",
        help="BigQuery Connection ID",
    )

    # GCS paths
    parser.add_argument(
        "--patient_gcs_uri",
        type=str,
        default="gs://<PROJECT_ID>-patient-profiles/*.txt",
        help="GCS URI pattern for patient profiles",
    )
    parser.add_argument(
        "--trials_gcs_uri",
        type=str,
        default="gs://<PROJECT_ID>-clinical-trials-docs/*.pdf",
        help="GCS URI pattern for clinical trial reports",
    )

    # Model
    parser.add_argument(
        "--model_name",
        type=str,
        default="<PROJECT_ID>.<DATASET_ID>.cssr_reports_model",
        help="Full path to the BQML Document Processing Model",
    )

    args = parser.parse_args()

    run_ingestion(
        project_id=args.project_id,
        dataset_id=args.dataset_id,
        connection_id=args.connection_id,
        patient_gcs_uri=args.patient_gcs_uri,
        trials_gcs_uri=args.trials_gcs_uri,
        model_name=args.model_name,
    )
