-- Copyright 2024 Google LLC
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

-- AUTO-GENERATED FILE: DO NOT EDIT DIRECTLY.
-- This file was generated by scripts/parameterize.py based on config.yaml
-- Source Template: sql/Parse Patient Profiles.sql

CREATE OR REPLACE PROCEDURE `<DATASET_ID>.IngestPatientProfiles`()
BEGIN
    EXECUTE IMMEDIATE """CREATE OR REPLACE EXTERNAL TABLE `<DATASET_ID>.patient_profiles`
WITH CONNECTION `<PROJECT_ID>.us.cloud_ai_resources` 
OPTIONS(
  object_metadata = 'SIMPLE',
  uris = ['gs://<PROJECT_ID>-patient-profiles/*.txt']
);""";
    EXECUTE IMMEDIATE """CREATE OR REPLACE TABLE`<DATASET_ID>.Patients` AS (
  SELECT
    uri,
    extracted_data.name,
    extracted_data.age,
    extracted_data.sex,
    extracted_data.place_of_residency,
    extracted_data.employment_status,
    extracted_data.primary_disorder,
    extracted_data.other_relevant_history,
    extracted_data.symptoms,
    extracted_data.performance_status,
    extracted_data.physical_status,
    extracted_data.laboratory_results,
    extracted_data.prior_therapy,
    extracted_data.current_plan
  FROM (
    SELECT
      uri,
      AI.GENERATE(
        STRUCT(
          \'\'\'
          You are a clinical data extraction assistant. Extract the patient profile information from the provided document.
          
          Requirements:
          1. Use the exact keys requested.
          2. If \"symptoms\" are listed, separate them into an array of strings.
          3. Combine multiple laboratory results into a single string.
          4. If a field like \"employment_status\" is not explicitly stated but can be heavily inferred (e.g., an 84-year-old is likely \"Retired\"), infer it. Otherwise, return null.
          \'\'\' AS prompt,
          OBJ.GET_ACCESS_URL(OBJ.MAKE_REF(uri, '<PROJECT_ID>.us.cloud_ai_resources'), 'r') AS document
        ),
        output_schema => \'\'\'
          name STRING,
          age STRING,
          sex STRING,
          place_of_residency STRING,
          employment_status STRING,
          primary_disorder STRING,
          other_relevant_history STRING,
          symptoms ARRAY<STRING>,
          performance_status STRING,
          physical_status STRING,
          laboratory_results STRING,
          prior_therapy STRING,
          current_plan STRING
        \'\'\',
        model_params => JSON '{\"generation_config\": {\"temperature\": 0.1, \"max_output_tokens\": 2048, \"thinking_config\": {\"include_thoughts\": true}}}',
        connection_id => '<PROJECT_ID>.us.cloud_ai_resources',
        endpoint => 'gemini-2.5-pro'
      ) AS extracted_data
    FROM
      `<DATASET_ID>.patient_profiles`
  )
);""";
END;
